# .gitignore for Lovable project

# Python
__pycache__/
*.py[cod]
*.pyo
*.pyd
*.env
*.venv
env/
venv/
ENV/
build/
dist/
*.egg-info/
*.egg

# VS Code
.vscode/

# OS files
.DS_Store
Thumbs.db

# Logs
*.log

# Environment variables
.env

# Node modules (if applicable)
node_modules/

# Coverage reports
htmlcov/
.coverage
coverage.xml
*.cover

# Database files
*.sqlite3
*.db

# Temporary files
*.tmp
*.bak
*.swp